### ISSUE TITLE
Enhance readme file

### ISSUE THREAD

**Issue by diva711** [Aryan-Chharia/Computer-Vision-Projects#2]
the readme file needs to be edited and to be made more elaborate. 
I can contribute to it, please assign it to me.

**Comment by Aryan-Chharia** [comment]
Go Ahead!

**Comment by Lonwwolf14** [comment]
@Aryan-Chharia Pull request created with updated README showcasing project results and media.

**Comment by Aryan-Chharia** [comment]
@Lonwwolf14 You are not assigned the issue. Check the pull request comment there.

**Comment by Aryan-Chharia** [comment]
@Lonwwolf14 

Steps to Contribute:

Find an Issue: Look for a problem or feature you'd like to work on.
Check Existing Issues: Review the list of open issues to ensure someone else isn't already working on it.
Create a New Issue: If your issue hasn't been covered, create a new one.
Review and Assignment: Once your issue is reviewed, it will be assigned to you.
Start Working: You can then begin working on the assigned issue.

If you're unsure about anything, join the GSSOC Discord, where you can ask questions. Hope this helps!

**Comment by Lonwwolf14** [comment]
Ohh I See 
I got it now...
